name: .NET Core - Packages Nuget

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100' # SDK Version to use.
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: dotnet build ./src/NetHacksPack.Core --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Core
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Core/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Data.Persistence.Abstractions --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Data.Persistence.Abstractions
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Data.Persistence.Abstractions/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Data.Persistence.EF --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Data.Persistence.EF
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Data.Persistence.EF/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Hosting.Abstractions --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Hosting.Abstractions
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Hosting.Abstractions/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Hosting --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Hosting
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Hosting/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Hosting.Environment --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Hosting.Environment
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Hosting.Environment/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Hosting.Connections --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Hosting.Connections
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Hosting.Connections/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Hosting.Listener --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Hosting.Listener
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Hosting.Listener/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Hosting.Web.IIS --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Hosting.Web.IIS
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Hosting.Web.IIS/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Integration.Abstractions --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Integration.Abstractions
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Integration.Abstractions/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Integration.RabbitMQ --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Integration.RabbitMQ
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Integration.RabbitMQ/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Integration.RabbitMQ.Handlers --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Integration.RabbitMQ.Handlers
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Integration.RabbitMQ.Handlers/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Core.Extensions.Events --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Core.Extensions.Events
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Core.Extensions.Events/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Database.Events --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Database.Events
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Database.Events/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate
        
      - run: dotnet build ./src/NetHacksPack.Database.Extension.EF --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Database.Extension.EF
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Database.Extension.EF/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Database.Extension.EFCore.Logging --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Database.Extension.EFCore.Logging
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Database.Extension.EFCore.Logging/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Database.Extensions.EFCore.Loggin.PostgreSql --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Database.Extensions.EFCore.Loggin.PostgreSql
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Database.Extensions.EFCore.Loggin.PostgreSql/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Database.Extensions.EFCore.Logging.SqlServer --configuration Release
      - name: Create the package Application
        run: dotnet pack -c Release ./src/NetHacksPack.Database.Extensions.EFCore.Logging.SqlServer
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Database.Extensions.EFCore.Logging.SqlServer/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Data.Linq.EF
      - name: Create the package NetHacksPack.Data.Linq.EF Application
        run: dotnet pack -c Release ./src/NetHacksPack.Data.Linq.EF
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/NetHacksPack.Data.Linq.EF/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate

      - run: dotnet build ./src/NetHacksPack.Integration.Azure
      - name: Create the package NetHacksPack.Integration.Azure
        run: dotnet pack -c Release ./src/NetHacksPack.Integration.Azure
      - name: Publish the package to Nuget Package Manager
        run: dotnet nuget push ./src/NetHacksPack.Integration.Azure/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate
        
      - run: dotnet build ./src/NetHacksPack.Notifications.Abstractions --configuration Release
      - name: Create the package NetHacksPack.Notifications.Abstractions
        run: dotnet pack -c Release ./src/NetHacksPack.Notifications.Abstractions
      - name: Publish the package NetHacksPack.Notifications.Abstractions to Nuget Package Manager
        run: dotnet nuget push ./src/NetHacksPack.Notifications.Abstractions/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate
        
      - run: dotnet build ./src/NetHacksPack.Notifications.Extensions.SmtpMail --configuration Release
      - name: Create the package NetHacksPack.Notifications.Extensions.SmtpMail
        run: dotnet pack -c Release ./src/NetHacksPack.Notifications.Extensions.SmtpMail
      - name: Publish the package NetHacksPack.Notifications.Extensions.SmtpMail to Nuget Package Manager
        run: dotnet nuget push ./src/NetHacksPack.Notifications.Extensions.SmtpMail/bin/Release/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate
